### PR TITLE
fix: ignore hidden and non .js files in loader

### LINKED ISSUE #110: Ignore hidden and non .js files in loader
> Ignore all files that have a . in front of the file name regardless of extension. And also ignore any other file that doesn't have a .js extension.

Related: #103

### PR DESCRIPTION
**Pull request by neojp**
Fixes #110

### CODE REVIEW

File: src/packages/fs/utils/is-js-file.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+// filter out hidden files && non .js files
+export default function isJsFile(file) {
```
Comment (zacharygolba) [inline src/packages/fs/utils/is-js-file.js]: Can we make this function named `isJSFile` for consistency with traditional capitalization for the JS abbreviation?

File: src/packages/loader/index.js [hunk 2]
```diff
@@ -1,4 +1,5 @@
 import fs from '../fs';
```
Comment (zacharygolba) [inline src/packages/loader/index.js]: I'm nitpicking but can we add an export from the main fs module (./packages/fs/index.js) like this:

```javascript
export default fs;
export isJSFile from './utils/is-js-file';
```

And then import in this file like:

```javascript
import fs, { isJSFile } from '../fs';
```

File: test/unit/packages/fs.js [hunk 3]
```diff
@@ -0,0 +1,34 @@
+import { expect } from 'chai';
+
+import isJsFile from '../../../src/packages/fs/utils/is-js-file';
+
+describe('Unit: class Fs ', () => {
```
Comment (zacharygolba) [inline test/unit/packages/fs.js]: We should use `class fs` since it's always imported that way (even though classes are traditionally upper camel cased).

**Comment by zacharygolba** [comment]
Once tests pass I'll merge this. Excellent work @neojp! 👏
