### PR TITLE
fix: query parameters are not added to custom routes

### LINKED ISSUE #522: Query parameters/whitelist not working for model-less controllers
Tested with both `page` as well as `page[number]`.

Request:
```
GET http://localhost:4000/employees?page=2
```

Controller:
```
query = [
     'page'
]
```

Relevant stacktrace:
```
[2016-11-12T20:42:48.736Z] TypeError: 'page' is not a valid parameter for this resource.
    at Map.validate (/node_modules/lux-framework/src/packages/router/route/params/parameter-group/index.js:61:17)
    at /node_modules/lux-framework/src/packages/router/route/index.js:153:27
    at Generator.next (<anonymous>)
    at step (/dist/bundle.js:235:30)
    at /dist/bundle.js:253:14
    at /dist/bundle.js:232:12
    at Set.visit (/dist/bundle.js:8435:7)
    at parseRequest.then.params (/node_modules/lux-framework/src/packages/server/index.js:119:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### PR DESCRIPTION
**Pull request by nickschot**
Fixes #522

### CODE REVIEW

File: test/test-app/app/controllers/custom.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
+import { Controller } from 'LUX_LOCAL';
+
+class CustomController extends Controller {
+  query = [
+    'userId'
+  ];
+
+  index({
```
Comment (zacharygolba) [inline test/test-app/app/controllers/custom.js]: No need to declare the `userId` variable here.

Comment (zacharygolba) [inline test/test-app/app/controllers/custom.js]: This would be a linter error but the test-app is ignored.

Comment (nickschot) [inline test/test-app/app/controllers/custom.js]: That does make the test fail though. Will poke you on gitter.
